[BYBIT]
api_public=
api_secret=
; demo/trade
mode=demo
; Для примера BTC/USDT, BTC/USDC:USDC, BTC/USDT:USDT-260403
tickers= BTC/USDT, BTC/USDC:USDC
[INDICATOR]
; 5m, 15m, 30m, 1h, 4h - только такие таймфреймы
timeframe=15m
obv_length=1
macd_fast=12
macd_slow=26
macd_signal=9
stoch_k=14
stoch_d=3
stoch_smooth=1
; Не больше 200
sma_lenght=200
[INDICATOR.WEIGHTS]
; Дробный величины указываются через точку
; Строго больше нуля
macd=0.1
stochastic=1
obv=1
ma=1
vol=1
[ORDER]
; volume_const указывается в BTC
volume_const=0.0015
; 10% для примера
volume_percent=10
leverage=10
; шаг сетки в процентах
grid_step_percent = 1
[RISK]
; в процентах
TP=1
SL=1
simple_TP_percent=60
trailing_trigger_percent=1
; в процентах
trailing_stop_percent=1
[PROXY]
; http://user:password@host:port
http=
[OTHER]
control_word=control_word